# Generated by Django 3.1 on 2020-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200829_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Accepted', 'Order Accepted'), ('Order Canceled', 'Order Canceled')], max_length=20),
        ),
    ]
