# Generated by Django 3.1 on 2020-08-30 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20200829_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_data',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='User_Profile.userprofile'),
            preserve_default=False,
        ),
    ]
