# Generated by Django 3.1 on 2020-08-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_data',
        ),
    ]
