# Generated by Django 3.1 on 2020-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
