# Generated by Django 3.1 on 2020-08-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0002_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(choices=[('customer', 'customer'), ('vendor', 'vendor')], max_length=50),
        ),
    ]
